# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=11)),
                ('dni', models.CharField(max_length=8)),
                ('n_canchas_sinteticas', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
                ('tipo_cancha_sintetica', models.CharField(max_length=20)),
                ('n_cuenta_corriente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('activo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
